version: '4.24'

services:
  mysqldb:
    container_name: mysql_spring
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/db_data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_spring
    restart: always
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "9090:80"

